### ISSUE TITLE
AndroidX compatibility

### ISSUE THREAD

**Issue by IGx89** [adobe/xamarin-aepassurance#24]
AndroidX compatibility would be helpful. We've removed all our v4/v7 compat libraries in our app, since everything that used them is now switched to AndroidX. When we attempt to use this library though, we get an exception about not finding class "android.support.v4.app.ActivityCompat" and have to manually add a dependency on Xamarin.Android.Support.Compat (which adds a bunch of older libraries) in order to get it to work.

**Comment by PravinPK** [comment]
@IGx89,  our current minimum for Android support is API 14. AndroidX requires API 15. We will look into bumping the minimum version of the underlying Android libraries and supporting AndroidX soon.

Thanks,
Pravin

**Comment by PravinPK** [comment]
@IGx89, We are working on a newer version of our Adobe SDK's Android libraries that would support Android X. We expect them to be released later this Fall.

Closing this issue for now.

Thanks,
Pravin
