### ISSUE TITLE
AssemblyName attribute of iOS library has ambiguous value

### ISSUE THREAD

**Issue by raginmari** [adobe/xamarin-aepassurance#26]
### Expected Behaviour

When I use both Adobe.AEPAssurance.iOS and Adobe.ACPUserProfile.iOS in my project, both libraries are available to me and work as expected.

### Actual Behaviour

When I use both Adobe.AEPAssurance.iOS and Adobe.ACPUserProfile.iOS in my project, NuGet discards the one with the lower version number because both libraries compile to "NativeLibrary.dll".

### Reproduce Scenario (including but not limited to)

Every build of iOS projects using both Adobe.AEPAssurance.iOS and Adobe.ACPUserProfile.iOS.

#### Steps to Reproduce

- Create new Xamarin.Forms project
- Add NuGet Adobe.AEPAssurance.iOS to iOS platform project
- Add NuGet Adobe.ACPUserProfile.iOS to iOS platform project
- Probably reference both in your code
- Build iOS project

#### Platform and Version

- Xamarin.Forms for iOS
- Adobe.AEPAssurance.iOS 1.0.0
- Adobe.ACPUserProfile.iOS 0.0.2

#### Sample Code that illustrates the problem

I cannot post any actual code, I'm afraid.

#### Logs taken while reproducing problem

Encountered conflict between 'Reference:/Users/XXX/.nuget/packages/adobe.acpuserprofile.ios/0.0.2/lib/xamarinios10/NativeLibrary.dll' and 'Reference:/Users/XXX/.nuget/packages/adobe.aepassurance.ios/1.0.0/lib/xamarinios10/NativeLibrary.dll'. Choosing 'Reference:/Users/XXX/.nuget/packages/adobe.aepassurance.ios/1.0.0/lib/xamarinios10/NativeLibrary.dll' because AssemblyVersion '1.0.0.0' is greater than '0.0.2.0'.

**Comment by cacheung** [comment]
We have a question about if you need to use the UserProfile features in your project.  
We will follow up this issue in https://github.com/adobe/xamarin-acpuserprofile/issues/3.
Closing this one.

**Comment by raginmari** [comment]
The [AssemblyName of the iOS library](https://github.com/adobe/xamarin-aepassurance/blob/main/src/Adobe.AEPAssurance.iOS/Adobe.AEPAssurance.iOS.csproj#L12) is still "NativeLibrary" which looks like an oversight and should be fixed.

**Comment by cacheung** [comment]
The clash between UserProfile and Assurance should be fixed after the UserProfile update.  We will fix the AssemblyName for Assurance when there is a new update for Assurance.
