### ISSUE TITLE
Add support for .NET MAUI

### ISSUE THREAD

**Issue by ChristopherStephan** [adobe/xamarin-aepassurance#27]
The support of Xamarin will end in May 2024. Packages targeting only Xamarin.Android or Xamarin.iOS will no longer work with MAUI. This library needs to be migrated to MAUI to continue using Adobe products in our app. Please let us know your plans on migrating this library to MAUI.

**Comment by cdhoffmann** [comment]
Hey @ChristopherStephan. Support for Xamarin has been dropped for a while. If anything changes, we will be sure to let you know on this ticket. For now i will be closing it.
